# Generated by Django 5.1.15 on 2026-09-28 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField(verbose_name='Ano')),
                ('imagen', models.CharField(help_text='Ruta relativa dentro de static/, ej: images/peliculas/dune.jpg', max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio de arriendo/venta, editable desde Django Admin.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='peliculas.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='peliculas.genero')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['-anio', 'titulo'],
            },
        ),
    ]
